import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import { Dumbbell, ArrowRight, Flame, Target, Zap, Brain, Salad, MessageCircle } from 'lucide-react';

const Index = () => {
  const { user, loading } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!loading && user) {
      navigate('/dashboard');
    }
  }, [user, loading, navigate]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="animate-pulse flex items-center gap-3">
          <div className="w-8 h-8 rounded-full gradient-primary" />
          <span className="text-lg font-display">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <div className="relative overflow-hidden">
        <div className="absolute inset-0 gradient-dark opacity-95" />
        <div className="absolute inset-0">
          <div className="absolute top-20 left-10 w-72 h-72 rounded-full bg-primary/20 blur-3xl" />
          <div className="absolute bottom-20 right-10 w-96 h-96 rounded-full bg-accent/20 blur-3xl" />
        </div>
        
        <div className="relative container mx-auto px-4 py-20 lg:py-32">
          {/* Navbar */}
          <nav className="flex items-center justify-between mb-16">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl gradient-primary fitness-shadow">
                <Dumbbell className="h-6 w-6 text-primary-foreground" />
              </div>
              <span className="text-xl font-display font-bold text-primary-foreground">AI Gym</span>
            </div>
            <Button 
              onClick={() => navigate('/auth')}
              variant="outline"
              className="border-primary-foreground/20 text-primary-foreground hover:bg-primary-foreground/10"
            >
              Get Started
            </Button>
          </nav>

          {/* Hero Content */}
          <div className="text-center max-w-4xl mx-auto space-y-8">
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-display font-bold text-primary-foreground leading-tight">
              Your AI-Powered
              <span className="text-gradient-primary block">Fitness Revolution</span>
            </h1>
            <p className="text-lg md:text-xl text-primary-foreground/70 max-w-2xl mx-auto">
              Meet your personal AI trainer, dietician, and fitness companion. Get personalized workout plans, meal suggestions, habit tracking, and real-time motivation.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
              <Button 
                size="lg"
                className="gradient-primary text-lg px-8 fitness-shadow"
                onClick={() => navigate('/auth')}
              >
                Start Your Journey
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              <Button 
                size="lg"
                variant="outline"
                className="border-primary-foreground/20 text-primary-foreground hover:bg-primary-foreground/10 text-lg px-8"
              >
                Watch Demo
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <section className="py-20 lg:py-32 bg-background">
        <div className="container mx-auto px-4">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <h2 className="text-3xl md:text-4xl font-display font-bold mb-4">
              Everything You Need to
              <span className="text-gradient-primary"> Transform</span>
            </h2>
            <p className="text-lg text-muted-foreground">
              A complete AI-powered fitness ecosystem designed to help you achieve your goals faster.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <FeatureCard
              icon={<Salad className="h-6 w-6" />}
              title="AI Dietician"
              description="Personalized meal plans, calorie tracking, and grocery lists generated by AI based on your goals."
              gradient="gradient-primary"
            />
            <FeatureCard
              icon={<Target className="h-6 w-6" />}
              title="Smart Workout Plans"
              description="AI-generated workout programs tailored to your fitness level, goals, and available equipment."
              gradient="gradient-accent"
            />
            <FeatureCard
              icon={<MessageCircle className="h-6 w-6" />}
              title="Virtual Gym Buddy"
              description="Your 24/7 AI companion for motivation, guidance, and celebrating your fitness milestones."
            />
            <FeatureCard
              icon={<Flame className="h-6 w-6" />}
              title="Habit Tracking"
              description="Smart habit analytics with behavioral insights and AI-powered schedule adjustments."
            />
            <FeatureCard
              icon={<Brain className="h-6 w-6" />}
              title="Mood-Aware Coaching"
              description="Sentiment analysis detects your mood and adjusts recommendations accordingly."
            />
            <FeatureCard
              icon={<Zap className="h-6 w-6" />}
              title="Progress Analytics"
              description="Comprehensive dashboards with insights on weight, workouts, calories, and achievements."
            />
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 gradient-dark relative overflow-hidden">
        <div className="absolute inset-0 opacity-30">
          <div className="absolute top-10 right-20 w-64 h-64 rounded-full bg-primary blur-3xl" />
          <div className="absolute bottom-10 left-20 w-80 h-80 rounded-full bg-accent blur-3xl" />
        </div>
        <div className="container mx-auto px-4 text-center relative z-10">
          <h2 className="text-3xl md:text-4xl font-display font-bold text-primary-foreground mb-4">
            Ready to Transform Your Fitness Journey?
          </h2>
          <p className="text-lg text-primary-foreground/70 mb-8 max-w-xl mx-auto">
            Join thousands who have already started their AI-powered fitness revolution.
          </p>
          <Button 
            size="lg"
            className="gradient-primary text-lg px-8 fitness-shadow"
            onClick={() => navigate('/auth')}
          >
            Get Started Free
            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 bg-card border-t">
        <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
          <p>© 2025 AI Gym Assistant. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

interface FeatureCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  gradient?: string;
}

const FeatureCard = ({ icon, title, description, gradient }: FeatureCardProps) => (
  <div className="group p-6 rounded-2xl bg-card border border-border hover:border-primary/50 transition-all hover:shadow-lg">
    <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 ${
      gradient ? `${gradient} text-primary-foreground` : 'bg-primary/10 text-primary'
    }`}>
      {icon}
    </div>
    <h3 className="text-xl font-display font-semibold mb-2">{title}</h3>
    <p className="text-muted-foreground">{description}</p>
  </div>
);

export default Index;
